### ISSUE TITLE
client.config.initialize() appears to not store path to sdk

### ISSUE THREAD

**Issue by gwarburton** [thycotic/secret-server-python#22]
https://stackoverflow.com/questions/57785074/how-to-fix-sdk-client-path-is-invalid-error-in-thycotic-secret-servers-api/
My env details:
OS: Windows Server 2008
Python: 3.8.2

**Describe the bug**
client.config.initialize() appears to not store path to sdk

**To Reproduce**
1. write a script that inits your sdk details
`from secret_server.sdk_client import SDK_Client`
`path_to_sdk = "C:\\tss\\secretserver-sdk-1.4.1-win-x64\\"`
`endpoint = "https://tss.domain.com/"`
`rule = "ruleName"`
`onboarding_key = "onboardingKeyValue"`
`client = SDK_Client()`
`client.config.SDK_CONFIG["path"] = path_to_sdk`
`client.config.SDK_CONFIG["url"] = endpoint`
`client.config.SDK_CONFIG["rule"] = rule`
`client.config.SDK_CONFIG["key"] = onboarding_key`
`client.commands.initialize()`

2. run the script
3. notice that the 3 config files are created (credentials, cache, endpoint)
4. write a second script to use the configs
`from secret_server.sdk_client import SDK_Client`
`client = SDK_Client()`
`pswd = client.commands.get_secret(1234, field = 'password')`
5. see error in output

> \lib\site-packages\secret_server\commands.py", line 19, in execute raise ValueError('SDK client path is invalid')

**Expected behavior**
pswd variable should now contain the value stored in the password field of secret 1234

**Screenshots**
not provided due to the fact that I do not want to share sensitive data about my secrets or application

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
I was able to solve the problem by restating the path to the sdk in Script B, so it looks like this:
`path_to_sdk = "C:\\tss\\secretserver-sdk-1.4.1-win-x64\\"`
`client = SDK_Client()`
`client.config.SDK_CONFIG["path"] = path_to_sdk`
`pswd = client.commands.get_secret(1234, field = 'password')`

**Comment by wsmelton** [comment]
This repo and Python package has been superseded by [thycotic/python-tss-sdk](thycotic/python-tss-sdk)
